%YAML 1.0
---
lmk2d:
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.14598999e+002, 1.53432007e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.15237999e+002, 1.95416000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.20697998e+002, 2.34942001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.28212997e+002, 2.69165985e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.40731995e+002, 3.05268005e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.60884995e+002, 3.34898010e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.81356003e+002, 3.54888000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.06912994e+002, 3.73170990e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.53112000e+002, 3.89963989e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.03791992e+002, 3.81381989e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.45334015e+002, 3.63652008e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.75510010e+002, 3.41041992e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 4.01229004e+002, 3.10654999e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 4.18385986e+002, 2.74597992e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 4.30915985e+002, 2.40576004e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 4.40367004e+002, 2.02046005e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 4.46723999e+002, 1.61248993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.33005005e+002, 1.17523003e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.49067993e+002, 1.04821999e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.71733994e+002, 1.02955002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.93501999e+002, 1.09069000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.13863998e+002, 1.17351997e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.96828003e+002, 1.20065002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.17466003e+002, 1.12300003e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.44431000e+002, 1.08082001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.72792999e+002, 1.10598000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.93833008e+002, 1.25925003e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.53065994e+002, 1.71358002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.48330994e+002, 1.99095993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.45128998e+002, 2.24429993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.45046997e+002, 2.47052002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.25783005e+002, 2.61752014e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.36209000e+002, 2.63876007e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.49112000e+002, 2.67984985e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.63118988e+002, 2.64778015e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.75473999e+002, 2.63385986e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.58139999e+002, 1.56606995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.72656998e+002, 1.49705994e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.93248001e+002, 1.51955002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.12427002e+002, 1.65578995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.93348999e+002, 1.68912003e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.71906006e+002, 1.67501999e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.03489990e+002, 1.68315002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.22459991e+002, 1.55811005e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.44907990e+002, 1.55697006e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.63487000e+002, 1.66078003e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.45515991e+002, 1.74457001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.20959991e+002, 1.73438995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.04313995e+002, 3.09230011e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.18757996e+002, 3.00188995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.38130997e+002, 2.92059998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.48582001e+002, 2.95128998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.59070007e+002, 2.93024994e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.80462006e+002, 3.01704010e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.01095001e+002, 3.14266998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.81915009e+002, 3.23678986e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.65843994e+002, 3.31082001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.49671997e+002, 3.31225006e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.32429993e+002, 3.29709015e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.19087997e+002, 3.21648010e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.08968002e+002, 3.08709991e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.35612000e+002, 3.08057007e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.48595993e+002, 3.08278992e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.62457001e+002, 3.08541992e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.94707001e+002, 3.13157990e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.63065002e+002, 3.10727997e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.48856995e+002, 3.11029999e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.35373001e+002, 3.09643005e+002 ]
rvec: !!opencv-matrix
   rows: 3
   cols: 1
   dt: f
   data: [ -3.84095125e-002, 2.97943020e+000, -2.36517668e-001 ]
tvec: !!opencv-matrix
   rows: 3
   cols: 1
   dt: f
   data: [ -4.54864092e-002, 8.72449484e-003, 8.55158710e+000 ]
f: 2000
eyeLandMark:
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.58292999e+002, 1.56078995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.60546997e+002, 1.60919006e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.63852005e+002, 1.65166000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.68072998e+002, 1.68813004e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.73026993e+002, 1.70998001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.78134995e+002, 1.72511993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.83535004e+002, 1.73158005e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.89020996e+002, 1.73207993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.94393005e+002, 1.72764008e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.99761993e+002, 1.72156998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.05136993e+002, 1.72048996e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.10358994e+002, 1.73376999e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.58279999e+002, 1.56069000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.61960007e+002, 1.50681000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.67544006e+002, 1.46957993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.73764008e+002, 1.44869995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.80233002e+002, 1.44440002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.86470001e+002, 1.45179001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.92432007e+002, 1.47063995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 1.97871002e+002, 1.50356995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.02296997e+002, 1.55037994e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.05651993e+002, 1.60582001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.08432999e+002, 1.66669998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 2.10356995e+002, 1.73367004e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.62997986e+002, 1.65304001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.59255005e+002, 1.69830994e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.54437012e+002, 1.73304993e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.48968994e+002, 1.76205994e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.43088989e+002, 1.78270004e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.36963989e+002, 1.78891998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.30691010e+002, 1.78617996e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.24362000e+002, 1.77645004e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.18286011e+002, 1.76046997e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.12190002e+002, 1.74688995e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.06022003e+002, 1.74281998e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.00058014e+002, 1.75352005e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.63036011e+002, 1.65319000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.58925995e+002, 1.58994003e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.53114990e+002, 1.54227005e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.46583008e+002, 1.51235001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.39661987e+002, 1.49901001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.32489014e+002, 1.49621002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.25306000e+002, 1.50608002e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.18605988e+002, 1.53153000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.12528992e+002, 1.57181000e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.07282990e+002, 1.62485001e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.03063995e+002, 1.68701004e+002 ]
   - !!opencv-matrix
      rows: 2
      cols: 1
      dt: f
      data: [ 3.00049011e+002, 1.75345993e+002 ]
